package com.polysocial.utils;

public class TemplateDealine {
    public String setContent(String name, String groupName, String deadline, String nameTeacher) {
        String sb ="<!DOCTYPE html>\n"
        		+ "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\"\n"
        		+ "    xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
        		+ "\n"
        		+ "<head>\n"
        		+ "    <meta charset=\"utf-8\">\n"
        		+ "    <meta name=\"viewport\" content=\"width=device-width\">\n"
        		+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
        		+ "    <meta name=\"x-apple-disable-message-reformatting\">\n"
        		+ "    <title></title>\n"
        		+ "    <style id=\"\" media=\"all\">\n"
        		+ "\n"
        		+ "       \n"
        		+ "        /* devanagari */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 200;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLFj_Z11lFc-K.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0900-097F, U+1CD0-1CF6, U+1CF8-1CF9, U+200C-200D, U+20A8, U+20B9, U+25CC, U+A830-A839, U+A8E0-A8FB;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* latin-ext */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 200;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLFj_Z1JlFc-K.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* latin */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 200;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLFj_Z1xlFQ.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* devanagari */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 300;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLDz8Z11lFc-K.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0900-097F, U+1CD0-1CF6, U+1CF8-1CF9, U+200C-200D, U+20A8, U+20B9, U+25CC, U+A830-A839, U+A8E0-A8FB;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* latin-ext */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 300;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLDz8Z1JlFc-K.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* latin */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 300;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLDz8Z1xlFQ.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* devanagari */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 400;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiEyp8kv8JHgFVrJJbecmNE.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0900-097F, U+1CD0-1CF6, U+1CF8-1CF9, U+200C-200D, U+20A8, U+20B9, U+25CC, U+A830-A839, U+A8E0-A8FB;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* latin-ext */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 400;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiEyp8kv8JHgFVrJJnecmNE.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* latin */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 400;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiEyp8kv8JHgFVrJJfecg.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* devanagari */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 500;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLGT9Z11lFc-K.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0900-097F, U+1CD0-1CF6, U+1CF8-1CF9, U+200C-200D, U+20A8, U+20B9, U+25CC, U+A830-A839, U+A8E0-A8FB;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* latin-ext */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 500;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLGT9Z1JlFc-K.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* latin */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 500;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLGT9Z1xlFQ.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* devanagari */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 600;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLEj6Z11lFc-K.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0900-097F, U+1CD0-1CF6, U+1CF8-1CF9, U+200C-200D, U+20A8, U+20B9, U+25CC, U+A830-A839, U+A8E0-A8FB;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* latin-ext */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 600;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLEj6Z1JlFc-K.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* latin */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 600;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLEj6Z1xlFQ.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* devanagari */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 700;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLCz7Z11lFc-K.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0900-097F, U+1CD0-1CF6, U+1CF8-1CF9, U+200C-200D, U+20A8, U+20B9, U+25CC, U+A830-A839, U+A8E0-A8FB;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* latin-ext */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 700;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLCz7Z1JlFc-K.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* latin */\n"
        		+ "        @font-face {\n"
        		+ "            font-family: 'Poppins';\n"
        		+ "            font-style: normal;\n"
        		+ "            font-weight: 700;\n"
        		+ "            font-display: swap;\n"
        		+ "            src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLCz7Z1xlFQ.woff2) format('woff2');\n"
        		+ "            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;\n"
        		+ "        }\n"
        		+ "        .mcam{\n"
        		+ "            color : orange;\n"
        		+ "        }\n"
        		+ "    </style>\n"
        		+ "\n"
        		+ "    <style>\n"
        		+ "        /* What it does: Remove spaces around the email design added by some email clients. */\n"
        		+ "        /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */\n"
        		+ "        html,\n"
        		+ "        body {\n"
        		+ "            margin: 0 auto !important;\n"
        		+ "            padding: 0 !important;\n"
        		+ "            height: 100% !important;\n"
        		+ "            width: 100% !important;\n"
        		+ "            background: #f1f1f1;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* What it does: Stops email clients resizing small text. */\n"
        		+ "        * {\n"
        		+ "            -ms-text-size-adjust: 100%;\n"
        		+ "            -webkit-text-size-adjust: 100%;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* What it does: Centers email on Android 4.4 */\n"
        		+ "        div[style*=\"margin: 16px 0\"] {\n"
        		+ "            margin: 0 !important;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* What it does: Stops Outlook from adding extra spacing to tables. */\n"
        		+ "        table,\n"
        		+ "        td {\n"
        		+ "            mso-table-lspace: 0pt !important;\n"
        		+ "            mso-table-rspace: 0pt !important;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* What it does: Fixes webkit padding issue. */\n"
        		+ "        table {\n"
        		+ "            border-spacing: 0 !important;\n"
        		+ "            border-collapse: collapse !important;\n"
        		+ "            table-layout: fixed !important;\n"
        		+ "            margin: 0 auto !important;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* What it does: Uses a better rendering method when resizing images in IE. */\n"
        		+ "        img {\n"
        		+ "            -ms-interpolation-mode: bicubic;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* What it does: Prevents Windows 10 Mail from underlining links despite inline CSS. Styles for underlined links should be inline. */\n"
        		+ "        a {\n"
        		+ "            text-decoration: none;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* What it does: A work-around for email clients meddling in triggered links. */\n"
        		+ "        *[x-apple-data-detectors],\n"
        		+ "        /* iOS */\n"
        		+ "        .unstyle-auto-detected-links *,\n"
        		+ "        .aBn {\n"
        		+ "            border-bottom: 0 !important;\n"
        		+ "            cursor: default !important;\n"
        		+ "            color: inherit !important;\n"
        		+ "            text-decoration: none !important;\n"
        		+ "            font-size: inherit !important;\n"
        		+ "            font-family: inherit !important;\n"
        		+ "            font-weight: inherit !important;\n"
        		+ "            line-height: inherit !important;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* What it does: Prevents Gmail from displaying a download button on large, non-linked images. */\n"
        		+ "        .a6S {\n"
        		+ "            display: none !important;\n"
        		+ "            opacity: 0.01 !important;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* What it does: Prevents Gmail from changing the text color in conversation threads. */\n"
        		+ "        .im {\n"
        		+ "            color: inherit !important;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* If the above doesn't work, add a .g-img class to any image in question. */\n"
        		+ "        img.g-img+div {\n"
        		+ "            display: none !important;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* What it does: Removes right gutter in Gmail iOS app: https://github.com/TedGoas/Cerberus/issues/89  */\n"
        		+ "        /* Create one of these media queries for each additional viewport size you'd like to fix */\n"
        		+ "\n"
        		+ "        /* iPhone 4, 4S, 5, 5S, 5C, and 5SE */\n"
        		+ "        @media only screen and (min-device-width: 320px) and (max-device-width: 374px) {\n"
        		+ "            u~div .email-container {\n"
        		+ "                min-width: 320px !important;\n"
        		+ "            }\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* iPhone 6, 6S, 7, 8, and X */\n"
        		+ "        @media only screen and (min-device-width: 375px) and (max-device-width: 413px) {\n"
        		+ "            u~div .email-container {\n"
        		+ "                min-width: 375px !important;\n"
        		+ "            }\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /* iPhone 6+, 7+, and 8+ */\n"
        		+ "        @media only screen and (min-device-width: 414px) {\n"
        		+ "            u~div .email-container {\n"
        		+ "                min-width: 414px !important;\n"
        		+ "            }\n"
        		+ "        }\n"
        		+ "    </style>\n"
        		+ "\n"
        		+ "\n"
        		+ "    <style>\n"
        		+ "        .primary {\n"
        		+ "            background: #17bebb;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .bg_white {\n"
        		+ "            background: #ffffff;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .bg_light {\n"
        		+ "            background: #f7fafa;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .bg_black {\n"
        		+ "            background: #000000;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .bg_dark {\n"
        		+ "            background: rgba(0, 0, 0, .8);\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .email-section {\n"
        		+ "            padding: 2.5em;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /*BUTTON*/\n"
        		+ "        .btn {\n"
        		+ "            padding: 10px 15px;\n"
        		+ "            display: inline-block;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .btn.btn-primary {\n"
        		+ "            border-radius: 5px;\n"
        		+ "            background: #17bebb;\n"
        		+ "            color: #ffffff;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .btn.btn-white {\n"
        		+ "            border-radius: 5px;\n"
        		+ "            background: #ffffff;\n"
        		+ "            color: #000000;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .btn.btn-white-outline {\n"
        		+ "            border-radius: 5px;\n"
        		+ "            background: transparent;\n"
        		+ "            border: 1px solid #fff;\n"
        		+ "            color: #fff;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .btn.btn-black-outline {\n"
        		+ "            border-radius: 0px;\n"
        		+ "            background: transparent;\n"
        		+ "            border: 2px solid #000;\n"
        		+ "            color: #000;\n"
        		+ "            font-weight: 700;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .btn-custom {\n"
        		+ "            color: rgba(0, 0, 0, .3);\n"
        		+ "            text-decoration: underline;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        h1,\n"
        		+ "        h2,\n"
        		+ "        h3,\n"
        		+ "        h4,\n"
        		+ "        h5,\n"
        		+ "        h6 {\n"
        		+ "            font-family: 'Poppins', sans-serif;\n"
        		+ "            color: #000000;\n"
        		+ "            margin-top: 0;\n"
        		+ "            font-weight: 400;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        body {\n"
        		+ "            font-family: 'Poppins', sans-serif;\n"
        		+ "            font-weight: 400;\n"
        		+ "            font-size: 15px;\n"
        		+ "            line-height: 1.8;\n"
        		+ "            color: rgba(0, 0, 0, .4);\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        a {\n"
        		+ "            color: #17bebb;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        table {}\n"
        		+ "\n"
        		+ "        /*LOGO*/\n"
        		+ "\n"
        		+ "        .logo h1 {\n"
        		+ "            margin: 0;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .logo h1 a {\n"
        		+ "            color: #17bebb;\n"
        		+ "            font-size: 24px;\n"
        		+ "            font-weight: 700;\n"
        		+ "            font-family: 'Poppins', sans-serif;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /*HERO*/\n"
        		+ "        .hero {\n"
        		+ "            position: relative;\n"
        		+ "            z-index: 0;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .hero .text {\n"
        		+ "            color: rgba(0, 0, 0, .3);\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .hero .text h2 {\n"
        		+ "            color: #000;\n"
        		+ "            font-size: 34px;\n"
        		+ "            margin-bottom: 0;\n"
        		+ "            font-weight: 200;\n"
        		+ "            line-height: 1.4;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .hero .text h3 {\n"
        		+ "            font-size: 24px;\n"
        		+ "            font-weight: 300;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .hero .text h2 span {\n"
        		+ "            font-weight: 600;\n"
        		+ "            color: #000;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .text-author {\n"
        		+ "            bordeR: 1px solid rgba(0, 0, 0, .05);\n"
        		+ "            max-width: 50%;\n"
        		+ "            margin: 0 auto;\n"
        		+ "            padding: 2em;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .text-author img {\n"
        		+ "            border-radius: 50%;\n"
        		+ "            padding-bottom: 20px;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .text-author h3 {\n"
        		+ "            margin-bottom: 0;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        ul.social {\n"
        		+ "            padding: 0;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        ul.social li {\n"
        		+ "            display: inline-block;\n"
        		+ "            margin-right: 10px;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        /*FOOTER*/\n"
        		+ "\n"
        		+ "        .footer {\n"
        		+ "            border-top: 1px solid rgba(0, 0, 0, .05);\n"
        		+ "            color: rgba(0, 0, 0, .5);\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .footer .heading {\n"
        		+ "            color: #000;\n"
        		+ "            font-size: 20px;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .footer ul {\n"
        		+ "            margin: 0;\n"
        		+ "            padding: 0;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .footer ul li {\n"
        		+ "            list-style: none;\n"
        		+ "            margin-bottom: 10px;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        .footer ul li a {\n"
        		+ "            color: rgba(0, 0, 0, 1);\n"
        		+ "        }\n"
        		+ "        #mcam{\n"
        		+ "            background-color : orange;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "        #tcam{\n"
        		+ "            color : orange;\n"
        		+ "        }\n"
        		+ "\n"
        		+ "\n"
        		+ "\n"
        		+ "        @media screen and (max-width: 500px) {}\n"
        		+ "    </style>\n"
        		+ "    <meta name=\"robots\" content=\"noindex, follow\">\n"
        		+ "</head>\n"
        		+ "\n"
        		+ "<body width=\"100%\" style=\"margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #f1f1f1;\">\n"
        		+ "    <center style=\"width: 100%; background-color: #f1f1f1;\">\n"
        		+ "        <div\n"
        		+ "            style=\"display: none; font-size: 1px;max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;\">\n"
        		+ "            &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;\n"
        		+ "        </div>\n"
        		+ "        <div style=\"max-width: 600px; margin: 0 auto;\" class=\"email-container\">\n"
        		+ "\n"
        		+ "            <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\"\n"
        		+ "                style=\"margin: auto;\">\n"
        		+ "                <tr>\n"
        		+ "                    <td valign=\"top\" class=\"bg_white\" style=\"padding: 1em 2.5em 0 2.5em;\">\n"
        		+ "                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
        		+ "                            <tr>\n"
        		+ "                                <td class=\"logo\" style=\"text-align: center;\">\n"
        		+ "                                    <h1><a href=\"#\" id=\"tcam\">Polysocial Team</a></h1>\n"
        		+ "                                </td>\n"
        		+ "                            </tr>\n"
        		+ "                        </table>\n"
        		+ "                    </td>\n"
        		+ "                </tr>\n"
        		+ "                <tr>\n"
        		+ "                    <td valign=\"middle\" class=\"hero bg_white\" style=\"padding: 2em 0 4em 0;\">\n"
        		+ "                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
        		+ "                            <tr>\n"
        		+ "                                <td style=\"padding: 0 2.5em; text-align: center; padding-bottom: 3em;\">\n"
        		+ "                                    <div class=\"text\">\n"
        		+ "                                        <h2>"+name+" bạn có một bài tập mới</h2>\n"
        		+ "                                    </div>\n"
        		+ "                                </td>\n"
        		+ "                            </tr>\n"
        		+ "                            <tr>\n"
        		+ "                                <td style=\"text-align: center;\">\n"
        		+ "                                    <div class=\"text-author\">\n"
        		+ "                                        <img src=\"https://caodang.fpt.edu.vn/wp-content/uploads/x18198154_10208600482868814_3469513_n.png.pagespeed.ic_.4_CcyctRxZ.png\" alt=\"\"\n"
        		+ "                                            style=\"width: 100px; max-width: 600px; height: auto; margin: auto; display: block;\">\n"
        		+ "                                        <h3 class=\"name\">Nhóm: "+groupName+"</h3>\n"
        		+ "                                        <span class=\"position\">Được đăng bởi: "+nameTeacher+"</span>\n"
        		+ "                                        <p><a href=\"#\" class=\"btn btn-primary\" id=\"mcam\" >Ngày hết hạn: "+deadline+"</a></p>\n"
        		+ "                                    </div>\n"
        		+ "                                </td>\n"
        		+ "                            </tr>\n"
        		+ "                        </table>\n"
        		+ "                    </td>\n"
        		+ "                </tr>\n"
        		+ "\n"
        		+ "            </table>\n"
        		+ "         \n"
        		+ "        </div>\n"
        		+ "    </center>\n"
        		+ "\n"
        		+ "    <script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-23581568-13\"></script>\n"
        		+ "    <script>\n"
        		+ "        window.dataLayer = window.dataLayer || [];\n"
        		+ "        function gtag() { dataLayer.push(arguments); }\n"
        		+ "        gtag('js', new Date());\n"
        		+ "\n"
        		+ "        gtag('config', 'UA-23581568-13');\n"
        		+ "    </script>\n"
        		+ "    <script defer\n"
        		+ "        src=\"https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993\"\n"
        		+ "        integrity=\"sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==\"\n"
        		+ "        data-cf-beacon='{\"rayId\":\"77e768fdbd856e43\",\"token\":\"cd0b4b3a733644fc843ef0b185f98241\",\"version\":\"2022.11.3\",\"si\":100}'\n"
        		+ "        crossorigin=\"anonymous\"></script>\n"
        		+ "</body>\n"
        		+ "\n"
        		+ "</html>";
        return sb;
    }

}
